lint:
	npm run lint;

scan:
	npm install &&\
    npm audit --audit-level=critical

build:
	echo "Building locally" &&\
	npm install &&\
	npm run build;
	
test:
	echo "Running tests locally" &&\
	npm run test:unit;

start:
	npm install &&\
	npm run dev;

stop:
	pass