version: "2.1"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
    - "8080:8080"
    command: [ "npm", "run", "dev"]
    env_file:
      - .env
  gateway:
    build:
      context: ./microservices/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
    - "8010:8010"
    command: [ "python", "app.py"]
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
  server-jpg:
    build:
      context: ./microservices/server-jpg
      dockerfile: Dockerfile
    container_name: server-jpg
    ports:
    - "8004:8004"
    command: [ "python", "app.py"]
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
  server-png:
    build:
      context: ./microservices/server-png
      dockerfile: Dockerfile
    container_name: server-png
    ports:
    - "8005:8005"
    command: [ "python", "app.py"]
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
  server-webp:
    build:
      context: ./microservices/server-webp
      dockerfile: Dockerfile
    container_name: server-webp
    ports:
    - "8006:8006"
    command: [ "python", "app.py"]
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3