version: "2.1"

services:
  server:
    build: ./
    container_name: server
    ports:
    - "8004:8004"
    command: [ "sh", "start.sh"]
    env_file:
      - .env
    volumes:
      - "./:/app"
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
  load-test:
    build: ./
    container_name: load-test-server
    ports:
    - "8004:8004"
    - "8089:8089"
    command: [ "sh", "load_test.sh"]
    env_file:
      - .env
    volumes:
      - "./:/app"
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
  unit-test:
    build: ./
    container_name: unit-test-server
    ports:
    - "8089:8089"
    command: [ "sh", "unit_test.sh"]
    env_file:
      - .env
    volumes:
      - "./:/app"
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
  audit:
    build: ./
    container_name: audit-server
    ports:
    - "8004:8004"
    command: [ "sh", "audit.sh"]
    env_file:
      - .env
    volumes:
      - "./:/app"
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3