version: "2.1"

services:
  server:
    build: ./
    container_name: server
    ports:
    - "8004:8004"
    command: [ "python", "app.py"]
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
  server_db:
    image: postgres:13.1
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3