version: "2.1"

services:
  server:
    build: ./
    container_name: server
    ports:
    - "8000:8000"
    command: [ "python", "main.py"]
    healthcheck:
      test: curl --fail http://localhost:8004/health/ || exit 1
      interval: 10s
      timeout: 3s
      retries: 3