apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_OBJECT_EXPIRES_IN: "$AWS_OBJECT_EXPIRES_IN"
  AWS_S3_BUCKET: "$AWS_S3_BUCKET"
  AWS_S3_REGION: "$AWS_S3_REGION"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
kind: ConfigMap
metadata:
  labels:
    app.service: server-env
  name: env
