apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.network/backend-default: "true"
  podSelector:
    matchLabels:
      app.network/backend-default: "true"
