# Instruction referenced from https://geshan.com.np/blog/2022/01/redis-docker/
# and here https://levelup.gitconnected.com/implement-api-caching-with-redis-flask-and-docker-step-by-step-9139636cef24
version: '2'

services:
  cache:
    image: redis:7.0.10-alpine
    container_name: rate-limiter-redis-cache
    restart: always
    ports:
      - '6379:6379' 
  api:
    build: .
    container_name: rate-limiter-api
    env_file:
      - .env
    volumes:
      - './main:/app/main'
    depends_on:
      - cache
    ports:
      - '8089:8089'



